name: labeler

on: [pull_request]

jobs:

  static-analysis:
    runs-on: ubuntu-latest
    name: 💿 Static analysis
    steps:
      - uses: actions/checkout@v3
      - name: 💿 Static analysis
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: github.sh
        env:
          SHELLCHECK_OPTS: -s bash -S warning -e SC1090 -e SC2010 -e SC2154

  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '50'
          m_max_size: '200'
          l_max_size: '450'
          fail_if_xl: 'true'
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
