on:
  pull_request:
  push:
    branches:
      - main

name: Tests
jobs:
  tests:
    name: "Run tests"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: "Install dependencies"
        run: ./install-dependencies.sh

      - name: "Tests"
        run: ./lib/bashunit
